# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "rust",
    "memory_usage",
    "cmd_duration",
    "line_break",
    "jobs",
    "character",
]


# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "|>"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
separator = "/"
style = "bold dimmed green"

[cmd_duration]
min_time = 4
prefix = "underwent "

[directory]
truncate_to_repo = false
truncatoin_length = 5

