# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  # systemd initrd is what reads tpm2-device= from crypttab, for TPM unlock later
  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices.cryptroot = {
    device = "/dev/disk/by-uuid/bfb5be95-98cf-4b62-b644-a88e8f7fa480";
    allowDiscards = true;
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dc05939c-265d-4449-8fa0-761dae9fc5d6";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/dc05939c-265d-4449-8fa0-761dae9fc5d6";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/dc05939c-265d-4449-8fa0-761dae9fc5d6";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9B27-F7D8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # btrbk's backup target on the second drive. Unlocked after boot with a key
  # kept on the encrypted root, not in the initrd, and nofail throughout: a
  # dead backup drive costs the backups, never the boot.
  environment.etc.crypttab.text = ''
    cryptbackup /dev/disk/by-partlabel/strix-backup /root/luks-backup.key nofail,discard
  '';
  fileSystems."/mnt/backup" = {
    device = "/dev/mapper/cryptbackup";
    fsType = "btrfs";
    options = [
      "nofail"
      "noatime"
      "compress=zstd"
    ];
  };

  # No disk swap: a plain partition would write RAM to disk unencrypted, and
  # zram covers it (suspend is S3, so there is no hibernation image to hold).
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
