# OpenResearch - `orx`, a local-first workspace that runs several coding agents
# in parallel over one repo and keeps a git-native tree of what each one tried.
#
# It is an orchestrator, not an agent: each session gets its own worktree and
# its own harness (claude / codex / opencode), and every run is pinned to the
# commit it ran against, so a result can be traced back to the code that
# produced it. `orx up` serves the dashboard on 127.0.0.1:4791 out of a local
# SQLite store.
#
# Not in nixpkgs (checked 2026-09-05), so it is built here from the GitHub tag.
#
# The build is a plain cargo build: rustls instead of native-tls and a bundled
# SQLite, so there is no system library to wire up, and the dashboard SPA is
# committed under ui/dist and embedded with rust-embed - no node or pnpm in the
# build path at all.
#
# Wrapped with git and openssh on PATH: it shells out to git for the worktree
# and experiment tree, and to ssh for `orx up --remote`. Neither is a build
# input, so unwrapped it would pick up whatever is in the ambient PATH.
#
# Do NOT run `orx install-skills`: it writes a skill into ~/.claude/, which is
# generated by homes/programs/claude-code.nix. Declare it there instead.
{
  lib,
  rustPlatform,
  fetchFromGitHub,
  makeBinaryWrapper,
  versionCheckHook,
  git,
  openssh,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "openresearch";
  version = "0.1.120";

  src = fetchFromGitHub {
    owner = "alphaXiv";
    repo = "OpenResearch";
    tag = "v${finalAttrs.version}";
    sha256 = "1i3imskv7rylivz6zdh71g59cr8pfy0rj5fg3yqi6mfvdhx5llf4";
  };

  cargoHash = "sha256-3MO41VHwn+xz2LnEgqTW6wjRI8PUjYOoc+eva0INWQg=";

  nativeBuildInputs = [ makeBinaryWrapper ];

  postInstall = ''
    wrapProgram $out/bin/orx \
      --prefix PATH : ${
        lib.makeBinPath [
          git
          openssh
        ]
      }
  '';

  # The suite drives real runs against a git repo and the openresearch.sh API,
  # neither of which the sandbox has.
  doCheck = false;

  nativeInstallCheckInputs = [ versionCheckHook ];
  versionCheckProgram = "${placeholder "out"}/bin/orx";
  versionCheckProgramArg = "--version";
  doInstallCheck = true;

  meta = {
    description = "Local-first workspace for running coding agents as parallel research agents";
    homepage = "https://openresearch.sh";
    changelog = "https://github.com/alphaXiv/OpenResearch/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.mit;
    mainProgram = "orx";
    platforms = lib.platforms.unix;
  };
})
