attribute = "pastel_pink"
keyword = "sirocco"
"keyword.directive" = "red" # -- preprocessor comments (#if in C)
namespace = "silver"
punctuation = "silver"
"punctuation.delimiter" = "silver"
operator = "silver"
special = "honey"
property = "white"
variable = "pastel_pink"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
"variable.parameter" = { fg = "pastel_pink" }
"variable.builtin" = "mint"
type = "indigo"
"type.builtin" = "white" # TODO: distinguish?
constructor = "emerald"
function = "light_blue"
"function.macro" = "test_pink"
"function.builtin" = "white"
tag = "orange"
comment = "sirocco"
constant = "white"
"constant.builtin" = "white"
string = "sirocco"
number = "chamois"
escape = "honey"
# used for lifetimes
label = "test_pink"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "#000" }
"ui.linenr" = { fg = "comet" }
"ui.linenr.selected" = { fg = "lilac" }
"ui.statusline" = { fg = "lilac", bg = "revolver" }
"ui.statusline.inactive" = { fg = "lavender", bg = "revolver" }
"ui.popup" = { bg = "revolver" }
"ui.window" = { fg = "bossanova" }
"ui.help" = { bg = "#7958DC", fg = "#171452" }

"ui.text" = { fg = "lavender" }
"ui.text.focus" = { fg = "white" }

"ui.selection" = { bg = "purple" }
"ui.selection.primary" = { bg = "purple" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.highlight" = { bg = "bossanova" }

"ui.menu.selected" = { fg = "revolver", bg = "white" }

diagnostic = { modifiers = ["underlined"] }

warning = "lightning"
error = "apricot"
info = "delta"
hint = "silver"

[palette]
white = "#ffffff"
lilac = "#dbbfef"
lavender = "#a4a0e8"
comet = "#5a5977"
bossanova = "#452859"
midnight = "#3b224c"
revolver = "#281733"

silver = "#cccccc"
sirocco = "#697C81"
mint = "#9ff28f"
almond = "#eccdba"
chamois = "#E8DCA0"
honey = "#efba5d"

apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6F44F0"

indigo = "#5269FF"
orange = "#fdba74"
light_blue = "#9DB7FE"
pastel_pink = "#f0abfc"
light_green = "#A6E22E"
candy_pink = "#F23969"
pastel_orange = "#FDBA74"
emerald = "#59dcd8"
dark_blue = "#4352B9"
red = "#E06C75"
purple = "#540099"
test_pink = "#E673FF"
