{ pkgs }:
with pkgs;
[
  # claude-code, opencode and codex are NOT listed here: their programs.*
  # modules in homes/programs/ install their own wrapped package and would
  # collide on bin/<name>. Every other agent CLI below comes from the
  # numtide/llm-agents flake rather than nixpkgs, whose releases track the tools
  # as they ship. `claude update` and friends are no-ops against the read-only
  # store - bump the llm-agents input instead.

  bubblewrap # Linux sandbox backend used by codex.
  nodejs-slim # Runtime for bundled codex system skills.

  # ---- claude-code companions ----
  # All four ship an `init`/`install` subcommand that writes hooks into
  # ~/.claude/settings.json and appends prose to ~/.claude/CLAUDE.md. Do NOT run
  # those: both files are generated by homes/programs/claude-code.nix, so an
  # imperative edit is clobbered on activation or fails (settings.json is a
  # mode-444 store symlink). The wiring is declared there instead.

  rtk # CLI output compressor: `rtk git status`, `rtk test`, `rtk grep`.
  # Wrapped as a PreToolUse/Bash hook so bash output is filtered before it
  # reaches the context.

  icm # persistent cross-session memory (`icm store` / `icm recall`), SQLite +
  # optional onnxruntime embeddings.

  graphify # builds a queryable knowledge graph of a repo (`graphify update .`,
  # `graphify query`). Complements ast-grep: ast-grep matches syntax, graphify
  # answers cross-file "what talks to what". Not in llm-agents, so this stays on
  # nixpkgs.

  # ---- file search ----

  fff-mcp # agent-oriented file/content search, exposed over MCP and registered
  # in homes/programs/ai-mcp.nix. Keeps a resident index, so it answers in
  # milliseconds where a fresh rg spawn takes seconds.
  #
  # NOTE: the `fff` attribute in nixpkgs is dylanaraps' bash file manager, a
  # completely unrelated project - this is dmtrKovalenko/fff.

  # ---- git worktrees ----

  worktrunk # `wt`: git worktree manager aimed at running several agents at
  # once. `wt switch --create <branch>` makes the branch and its worktree in
  # one step, `wt list` aggregates status across all of them, and lifecycle
  # hooks run per-worktree setup/teardown (deps, .env, services).
  #
  # Shell integration ships as $out/share/nushell/vendor/autoload/wt.nu, which
  # nushell already scans, so do NOT run `wt config shell install`: it would
  # append a duplicate to a config file this repo generates.

  # ---- not in nixpkgs, built from packages/ai/ ----

  (callPackage ./ai/symposium.nix { }) # `cargo agents`: matches the workspace
  # dependency graph against plugin manifests and installs the skills, hooks and
  # MCP servers those crates ship for their own version. Rust-specific, and the
  # reason rtk is above - the recommendations registry points at it too.
  #
  # Configured in homes/programs/symposium.nix, which pins hook-scope to
  # "project". Do NOT run `cargo agents init`: at the default global scope it
  # merges hook entries straight into ~/.claude/settings.json, a mode-444 store
  # symlink here, so the write fails.

  (callPackage ./ai/crw.nix { }) # fastCRW: web scrape, crawl, map and search.
  # Puts `crw` on PATH; the `crw-mcp` binary from the same derivation is
  # registered in homes/programs/crw.nix.
  #
  # The build is nixpkgs' `fastcrw`, so it substitutes instead of compiling;
  # ./ai/crw.nix is just the renderer wrapper nixpkgs leaves out.
  #
  # Wraps in both LightPanda and chromium, so JS rendering works out of the box.
  # That is where the ~700 MB of closure comes from; the wrapper in crw.nix is
  # the one place to cut it.
  #
  # Do NOT run `crw setup` or `npx crw-mcp install` - both write MCP entries
  # into ~/.claude/settings.json and prose into ~/.claude/CLAUDE.md, the two
  # generated files. The equivalent wiring is declared in nix already.

  (callPackage ./ai/revdiff.nix { }) # diff review TUI: comment on lines, quit,
  # and the comments come back to the agent as `## file:line` markdown. Its
  # skill is registered for all three agents in homes/programs/ai-skills.nix,
  # and its launcher opens revdiff as a Zellij floating pane - plain Ghostty is
  # not enough, that backend is macOS-only. Not in nixpkgs (checked 2026-09-14).
  #
  # Do NOT run `/plugin install revdiff@revdiff`, `codex plugin add` or its
  # opencode setup.sh - each writes into config generated here.

  (callPackage ./ai/hyperresearch.nix { }) # deep research pipeline with a
  # persistent source vault. Its `deep-research` skill is registered for all
  # three agents in homes/programs/ai-skills.nix; the pipeline itself installs
  # per project on first use. Not in nixpkgs (checked 2026-09-28).
  #
  # Do NOT run `hyperresearch install --global`, `/plugin install`, `codex plugin
  # add` or `npx skills add` - each writes into config generated here.

  # ---- from the numtide/llm-agents flake ----
  # Bound by the overlay in machines/strix/default.nix, whose cache substitutes
  # most of them; the rest are in nixpkgs nowhere.

  reasonix # DeepSeek-native coding agent. Its provider key is decrypted
  # directly to ~/.reasonix/.env by the strix Home Manager config, and the
  # overlay wraps the binary with the two env defaults this machine wants
  # there. Do NOT run `reasonix upgrade`: bump the llm-agents input instead.

  openresearch # `orx`: runs claude-code/codex/opencode as parallel sessions over
  # one repo, each in its own worktree, and records every run in a git-native
  # experiment tree pinned to the commit it ran against. `orx up` serves a
  # dashboard on 127.0.0.1:4791 over local SQLite. Also ships key-free paper
  # retrieval - `orx discover` (alphaXiv full-text BM25 with page snippets,
  # OpenAlex, bioRxiv) and `orx paper --full` for extracted full text, which
  # SearXNG's research category cannot give.
  #
  # Overlaps worktrunk above on parallel worktrees; the experiment tree is the
  # part neither that nor graphify does. Do NOT run `orx install-skills` or
  # `orx update`: the first writes a skill into ~/.claude/, the second targets
  # the read-only store.

  terminal-browser # a real Chromium in a terminal pane, over the kitty graphics
  # protocol - ghostty speaks it, so `open --split right` puts a live page beside
  # the conversation, and `terminal-browser action` is an agent-browser
  # compatible CLI onto that same visible tab. Its skill is registered in
  # homes/programs/ai-skills.nix.
  #
  # The Electron it bundles is a zenbu-labs fork with terminal rendering
  # patches, so nixpkgs' electron is not a substitute and a local build would
  # mean carrying the fork - upstream's expression is used as-is.
  #
  # Do NOT run `terminal-browser setup` (writes the agent skills that
  # ai-skills.nix already installs) or `terminal-browser upgrade` (targets the
  # read-only store).

  nono # capability-based sandbox for agents: `nono run -- claude`.
  #
  # On NixOS its ELF resolver cannot find libc.so.6 for libgcc_s.so.1, so the
  # command_policies feature is broken; filesystem/network confinement, which is
  # what this is used for, is unaffected.

  tuicr # code review in the terminal: one GitHub-style continuous diff over
  # every changed file, line/range/file/review comments, vim keybindings, and
  # sessions that survive a restart. Reads git, jj and Mercurial, so `tuicr -w`
  # reviews uncommitted changes whichever a repo uses, and it pushes a real
  # review back through the forge's own CLI - `gh`, which
  # packages/basic_cli_set.nix already installs; `glab`, `bkt` and `tea` are not
  # installed, so GitHub is the forge that works here.
  #
  # The same job as revdiff above, pointed the other way: revdiff hands an agent
  # `## file:line` markdown to act on, while tuicr is the human's tool and a
  # comment goes to the forge rather than into the conversation.
  #
  # Config is ~/.config/tuicr/config.toml and saved reviews land under
  # ~/.local/share/tuicr/reviews; this repo writes neither. Do NOT run `tuicr
  # update`: from a store path it resolves itself to InstallMethod::Nix and runs
  # `nix profile upgrade '.*tuicr.*'`, which no profile here owns; bump the
  # llm-agents input instead.

  herdr # agent multiplexer: a background server owns the real terminals, and a
  # pane running an agent is marked idle, working or blocked from what it draws
  # on screen. Local and saved SSH machines sit in one TUI, and the CLI and
  # socket API are the same surface an agent drives - split a pane, prompt a
  # neighbour, wait until it is genuinely blocked instead of firing keystrokes.
  #
  # It does not wrap or replace the agents above, it owns their terminals, which
  # is why its integrations are declared where those agents are configured
  # (claude-code.nix, codex.nix, opencode.nix) rather than here. Do NOT run
  # `herdr integration install <agent>`: it writes ~/.claude/settings.json,
  # ~/.codex/hooks.json and opencode's cli.json, all generated read-only store
  # symlinks, so the write fails.
  #
  # Its skill is registered in homes/programs/ai-skills.nix. Do NOT run `herdr
  # update`: it recognizes a store path and says Nix installs update through Nix,
  # so this is another llm-agents bump. `[update] version_check` defaults on with
  # no environment override, and silencing it needs a generated
  # ~/.config/herdr/config.toml - which herdr's own Settings UI also writes, so
  # that file is left alone until the check actually annoys.

  codegraph # semantic code intelligence: `codegraph init` builds an index for a
  # project, then query/explore/sync read it. llm-agents' reasonix depends on it,
  # so taking the flake's copy for PATH means one store path serves both.
  #
  # The index is per project and lives in `.codegraph/` inside the repo, which
  # `codegraph init` creates - so a repo that wants it wants that path ignored.
  # Nothing here runs init.

  ccusage # what the coding agents have actually spent, read from the logs they
  # already write on this machine. Claude Code, Codex and OpenCode are supported;
  # reasonix is not. Nothing is uploaded, and the cost it prints is
  # API-equivalent rather than money - these agents run on subscriptions, which
  # is exactly why its numbers are worth looking at.
  #
  # Wired into the prompt: homes/programs/ccusage.nix renders the active Claude
  # usage block (notional cost and time until it resets) as a starship segment.
  # `ccusage daily --json -O` is the cross-agent report to run by hand.

  ck # semantic + hybrid grep: `ck --sem` finds code by meaning, `ck -n` is
  # drop-in ripgrep, and `ck --hybrid` fuses the two with reciprocal rank
  # fusion - the fusion is the part nothing else here does. `ck --tui` is also
  # the only interactive search UI in this file: fff is MCP-only, and codegraph
  # and graphify are one-shot CLIs.
  #
  # Registered as an MCP server in homes/programs/ai-mcp.nix, where it holds the
  # semantic-search slot.
  #
  # Things 0.7.11 does that surprise: it AST-chunks only 14 languages (no nix,
  # no nushell, so a nix repo falls back to plain text); the index is
  # `<search-root>/.ck/` and is NOT relocatable - CK_INDEX_DIR does nothing - so
  # a repo wants that path ignored and a read-only root fails outright; there is
  # no execution provider at all (upstream #77, GPU unused); and it sizes its ort
  # thread pool from the core count, which is why the overlay wraps it in
  # `taskset` rather than leaving it to take all 32 here.
  #
  # Cost measured on this machine: first index of the 56-file `homes/` tree, 13s
  # and 6m34s of CPU; the same query again, 1.5s. bge-small is the speed pick -
  # the docs' words are "trades some accuracy for speed", 400-token chunks,
  # ~128 MiB - and `--switch-model jina-code|nomic-v1.5` re-indexes at 1024-token
  # chunks for ~500 MiB. No custom model or external-embedding-API path exists
  # yet; `--rerank` is the cheaper quality lever if bge-small proves too blunt.

  funes # memory of past agent sessions: a local Lance index plus pinned
  # embedding/reranking models, exposed as `recall`/`get` over MCP from
  # homes/programs/ai-mcp.nix. The semantic half of the pair with `icm` above,
  # which is keyed and cheap.
  #
  # llm-agents carries the AVX-512 VNNI patch lance needs, so nothing here swaps
  # the rust toolchain in any more.
  #
  # Do NOT run `funes add <agent>`, `funes update` or the curl installer: the
  # first writes hooks and MCP entries into agent config generated here, the
  # others target the read-only store. Never `funes push` - it publishes the
  # memory to the Hugging Face Hub.

  jscpd # copy-paste detection. Overlaps scb-check's `clone_loc`, but where that
  # is one aggregate number jscpd names the pairs: each clone carries first and
  # second file with start/end lines, a kind (exact, renamed, similar, gap, ast,
  # semantic) and a token count. `--baseline-from-ref <ref>` re-scans a git ref's
  # tree and marks clones absent from it with `isNew`, so a diff-scoped "did this
  # change add duplication" is one scan rather than two.
  #
  # Wired into the diff-metrics skill (homes/programs/skills/diff-metrics). Note
  # it has no grammar for nix or nushell - supported formats include rust, python,
  # ts and go - so here it only sees the python, bash, json and markdown files,
  # and data files it does parse inflate the percentage. Use it on code repos,
  # not on nix.

  plannotator-tui # annotate markdown in the terminal and hand the review back
  # as numbered feedback. The gap it fills: revdiff and tuicr above review code,
  # and what these agents produce first - `writing-plans` plans, hyperresearch
  # reports, `openspec` specs - is markdown that had no review step at all.
  #
  # `plannotator-tui <file.md>` opens it, `plannotator-tui last --host claude`
  # picks the agent's most recent reply to annotate, and `--export <file.md>`
  # prints the numbered feedback to paste back into a session. Its only delivery
  # path into a live pane is `herdr open --deliver-to <pane>`; annotations live
  # in ~/.plannotator rather than in the file, so the rest are pasted by hand.

  agent-browser # headless browser automation CLI for agents: navigate, snapshot,
  # click, fill, eval, against a real Chrome. Distinct from crw above, which
  # fetches and converts pages for reading - this one drives a page.
  # terminal-browser ships its own copy under lib/terminal-browser/agent-browser
  # for `terminal-browser action`, but that copy is not on PATH; this is the one
  # every agent can reach.
  #
  # It needs a browser: `agent-browser install` downloads its own Chromium into
  # its cache, or `--auto-connect` / `connect <port|url>` reuse one that is
  # already running - packages/basic_cli_set.nix installs chromium. Its skills
  # are documentation it prints on request (`agent-browser skills get core`), not
  # something to install.

  mcptoon # compresses MCP tool listings and results - `manifest --slim`, and
  # `call <server> <tool> --toon` - which is the one context consumer rtk does
  # not touch: rtk filters bash output, and MCP results arrive as tool results.
  #
  # The overlay wraps it with MCPTOON_SKIP_SELF_HEAL=1 because upstream installs
  # a skill into every agent's config directory on any invocation. Its gateway
  # mode is the do-not-run set - `mcptoon quickstart`, `mcptoon discover --write`
  # and `mcptoon skills sync` take over agent MCP config, which
  # homes/programs/ai-mcp.nix owns. `mcptoon off` / `restore` / `uninstall` undo
  # exactly those writes, so they are for a machine that took it up.
  #
  # It keeps its own server list in ~/.mcptoon/config.json (MCPTOON_CONFIG_FILE
  # moves it), which `mcptoon call` and `manifest` read. Nothing here writes it.
]
