{ pkgs }:
with pkgs;
[
  # claude-code itself is NOT listed here: programs.claude-code in
  # homes/programs/claude-code.nix installs its own wrapped `finalPackage`, and
  # having both in home.packages collides on bin/claude.
  #
  # opencode is absent for the same reason: programs.opencode in
  # homes/programs/opencode.nix puts it in home.packages itself, and would
  # collide on bin/opencode. `opencode upgrade` is likewise a no-op against the
  # read-only store, which is why autoupdate is turned off there.
  #
  # codex too, via programs.codex in homes/programs/codex.nix - same collision
  # on bin/codex, and `codex update` fails the same way, which is why
  # check_for_update_on_startup is false there.
  #
  # All three, and every other agent CLI below that numtide/llm-agents.nix
  # packages, come from that flake rather than nixpkgs - the overlay in
  # machines/strix/default.nix is where those names are bound, and flake.nix
  # says why. Its releases track the tools as they ship, where nixpkgs lags by
  # days. `claude update` is still a no-op here (the store is read-only) -
  # bump the llm-agents input instead, or run it off mise/npm if you need
  # same-day releases.

  bubblewrap # Linux sandbox backend used by codex.
  nodejs-slim # Runtime for bundled codex system skills.

  # ---- claude-code companions ----
  # All four below ship an `init`/`install` subcommand that writes hooks into
  # ~/.claude/settings.json and appends prose to ~/.claude/CLAUDE.md. Do NOT run
  # those - both files are generated by homes/programs/claude-code.nix, so an
  # imperative edit is either clobbered on the next activation or fails outright
  # (home-manager installs settings.json as a mode-444 store symlink). The
  # equivalent wiring is declared there instead.

  rtk # CLI output compressor: `rtk git status`, `rtk test`, `rtk grep`.
  # Wrapped as a PreToolUse/Bash hook so bash output is filtered before it
  # reaches the context. llm-agents 0.50.0 - nixpkgs has 0.49.0.

  icm # persistent cross-session memory (`icm store` / `icm recall`), SQLite +
  # optional onnxruntime embeddings. llm-agents 0.10.65 - nixpkgs has 0.10.63.

  graphify # builds a queryable knowledge graph of a repo (`graphify update .`,
  # `graphify query`). Complements ast-grep: ast-grep matches syntax, graphify
  # answers cross-file "what talks to what". Not in llm-agents, so this one
  # stays on nixpkgs - 0.9.66 at this pin.

  # ---- file search ----

  fff-mcp # agent-oriented file/content search, exposed over MCP and registered
  # in homes/programs/ai-mcp.nix. Keeps a resident index, so it answers in
  # milliseconds where a fresh rg spawn takes seconds.
  #
  # NOTE: the `fff` attribute in nixpkgs is dylanaraps' bash file manager, a
  # completely unrelated project - this is dmtrKovalenko/fff.
  # nixpkgs 0.10.6 == upstream v0.10.6 (current).

  # ---- git worktrees ----

  worktrunk # `wt`: git worktree manager aimed at running several agents at
  # once. `wt switch --create <branch>` makes the branch and its worktree in
  # one step, `wt list` aggregates status across all of them, and lifecycle
  # hooks run per-worktree setup/teardown (deps, .env, services).
  #
  # Nothing to add to nushell.nix: the shell integration - the `wt` wrapper
  # that actually cd's the session, plus completions - ships as
  # $out/share/nushell/vendor/autoload/wt.nu, and nushell already scans
  # /etc/profiles/per-user/yt/share/nushell/vendor/autoload. So do NOT run
  # `wt config shell install`; it would append a duplicate to a config file
  # this repo generates. nixpkgs 0.74.0 == upstream v0.74.0 (current).

  # ---- not in nixpkgs, built from packages/ai/ ----

  (callPackage ./ai/funes.nix { }) # memory of past agent sessions, MCP server
  # is `funes mcp` (registered in homes/programs/ai-mcp.nix). Local Lance index
  # plus pinned embedding/reranking models it downloads on first run.
  #
  # Do NOT run `funes add <agent>`, `funes update` or the curl installer - the
  # first writes hooks and MCP entries into the generated agent configs, the
  # others target the read-only store. And never `funes push`: it publishes
  # the memory to the Hugging Face Hub.

  (callPackage ./ai/symposium.nix { }) # `cargo agents`: matches the workspace
  # dependency graph against plugin manifests and installs the skills, hooks and
  # MCP servers those crates ship for their own version. Rust-specific, and the
  # reason rtk is above - the recommendations registry points at it too.
  #
  # Configured declaratively in homes/programs/symposium.nix. Do NOT run
  # `cargo agents init`: at the default global hook scope it merges hook entries
  # straight into ~/.claude/settings.json, which is a mode-444 store symlink
  # here, so the write fails. That config pins hook-scope to "project" instead.

  (callPackage ./ai/crw.nix { }) # fastCRW: web scrape, crawl, map and search.
  # Puts `crw` on PATH; the `crw-mcp` binary from the same derivation is
  # registered in homes/programs/crw.nix.
  #
  # The build is nixpkgs' `fastcrw` now, so it substitutes instead of compiling.
  # ./ai/crw.nix is down to the renderer wrapper nixpkgs leaves out.
  #
  # Wraps in both renderers - LightPanda (packages/ai/lightpanda.nix) and
  # chromium - so JS rendering works out of the box. That is where the ~700 MB
  # of closure comes from; the wrapper in crw.nix is the one place to cut it.
  #
  # Do NOT run `crw setup` or `npx crw-mcp install` - both write MCP entries
  # into ~/.claude/settings.json and prose into ~/.claude/CLAUDE.md, the two
  # generated files. The equivalent wiring is declared in nix already.

  (callPackage ./ai/revdiff.nix { }) # diff review TUI: comment on lines, quit,
  # and the comments come back to the agent as `## file:line` markdown. Its
  # skill is registered for all three agents in homes/programs/ai-skills.nix,
  # and its launcher opens revdiff as a Zellij floating pane - plain Ghostty is
  # not enough, that backend is macOS-only. Not in nixpkgs (checked 2026-09-14).
  #
  # Do NOT run `/plugin install revdiff@revdiff`, `codex plugin add` or its
  # opencode setup.sh - each writes into config generated here.

  (callPackage ./ai/hyperresearch.nix { }) # deep research pipeline with a
  # persistent source vault. Its `deep-research` skill is registered for all
  # three agents in homes/programs/ai-skills.nix; the pipeline itself installs
  # per project on first use. Not in nixpkgs (checked 2026-09-28).
  #
  # Do NOT run `hyperresearch install --global`, `/plugin install`, `codex plugin
  # add` or `npx skills add` - each writes into config generated here.

  # ---- from the numtide/llm-agents flake ----
  # These four, plus the claude-code, codex, opencode, rtk and icm entries
  # above, are the flake's packages: the overlay in machines/strix/default.nix
  # is where they are bound to these names, and its cache is a substituter
  # there, so none of them compile on this machine. Nono is in nixpkgs too, but
  # the flake's copy is newer; the rest are in nixpkgs nowhere.

  reasonix # DeepSeek-native coding agent. Its provider key is decrypted
  # directly to ~/.reasonix/.env by the strix Home Manager config, and the
  # overlay wraps the binary with the two env defaults this machine wants
  # there. Was packages/ai/reasonix.nix, pinned at 1.39.2; the flake has
  # 1.39.6. Do NOT run `reasonix upgrade`: bump the llm-agents input instead.

  openresearch # `orx`: runs claude-code/codex/opencode as parallel sessions over
  # one repo, each in its own worktree, and records every run in a git-native
  # experiment tree pinned to the commit it ran against. `orx up` serves a
  # dashboard on 127.0.0.1:4791 over local SQLite. Also ships key-free paper
  # retrieval - `orx discover` (alphaXiv full-text BM25 with page snippets,
  # OpenAlex, bioRxiv) and `orx paper --full` for extracted full text, which
  # SearXNG's research category cannot give.
  #
  # Overlaps worktrunk above on parallel worktrees; the experiment tree is the
  # part neither that nor graphify does. Was packages/ai/openresearch.nix at
  # 0.1.120; the flake has 0.2.10, so the CLI has had a minor release since
  # anything here was run against it. Their expression wraps git, ssh,
  # coreutils, procps, gnutar and xdg-utils onto PATH - a superset of the
  # git+ssh wrapper this repo carried - and sets ORX_NO_UPDATE_CHECK, so
  # nothing needed re-applying. Do NOT run `orx install-skills` or `orx update`:
  # the first writes a skill into ~/.claude/, the second targets the read-only
  # store.

  terminal-browser # a real Chromium in a terminal pane, over the kitty graphics
  # protocol - ghostty speaks it, so `open --split right` puts a live page beside
  # the conversation, and `terminal-browser action` is an agent-browser
  # compatible CLI onto that same visible tab. Its skill is registered in
  # homes/programs/ai-skills.nix.
  #
  # The Electron it bundles is a zenbu-labs fork with terminal rendering
  # patches, so nixpkgs' electron is not a substitute and a local build would
  # mean carrying the fork - upstream's expression is used as-is.
  #
  # Do NOT run `terminal-browser setup` (installs the agent skills into the
  # generated config, which ai-skills.nix already does) or `terminal-browser
  # upgrade` (targets the read-only store).

  nono # capability-based sandbox for agents: `nono run -- claude`.
  # llm-agents 0.79.0; nixpkgs has 0.74.0, which is why this moved. That
  # derivation runs no tests at all, so the note that used to be here - that
  # nixpkgs skips nono's command_policies tests because its ELF resolver cannot
  # find libc.so.6 for libgcc_s.so.1, leaving that feature broken on NixOS - is
  # about the nixpkgs build. Whether 0.79.0 fixed the feature itself has not
  # been re-measured here. Filesystem/network confinement, which is what this
  # is used for, is unaffected either way.
]
