{ pkgs }:
with pkgs;
[
  # claude-code itself is NOT listed here: programs.claude-code in
  # homes/programs/claude-code.nix installs its own wrapped `finalPackage`, and
  # having both in home.packages collides on bin/claude.
  #
  # opencode is absent for the same reason: programs.opencode in
  # homes/programs/opencode.nix puts it in home.packages itself, and would
  # collide on bin/opencode. `opencode upgrade` is likewise a no-op against the
  # read-only store, which is why autoupdate is turned off there.
  #
  # nixpkgs tracks upstream closely but can lag by a few days. `claude update`
  # is a no-op here (the store is read-only) - bump nixpkgs instead, or run it
  # off mise/npm if you need same-day releases.

  # ---- claude-code companions ----
  # All four below ship an `init`/`install` subcommand that writes hooks into
  # ~/.claude/settings.json and appends prose to ~/.claude/CLAUDE.md. Do NOT run
  # those - both files are generated by homes/programs/claude-code.nix, so an
  # imperative edit is either clobbered on the next activation or fails outright
  # (home-manager installs settings.json as a mode-444 store symlink). The
  # equivalent wiring is declared there instead.

  rtk # CLI output compressor: `rtk git status`, `rtk test`, `rtk grep`.
  # Wrapped as a PreToolUse/Bash hook so bash output is filtered before it
  # reaches the context. nixpkgs 0.45.0 == upstream v0.45.0 (current).

  icm # persistent cross-session memory (`icm store` / `icm recall`), SQLite +
  # optional onnxruntime embeddings. nixpkgs 0.10.53, upstream icm-v0.10.61 -
  # eight patch releases behind.

  graphify # builds a queryable knowledge graph of a repo (`graphify update .`,
  # `graphify query`). Complements ast-grep: ast-grep matches syntax, graphify
  # answers cross-file "what talks to what". nixpkgs 0.9.28, upstream v0.9.48.

  # ---- git worktrees ----

  worktrunk # `wt`: git worktree manager aimed at running several agents at
  # once. `wt switch --create <branch>` makes the branch and its worktree in
  # one step, `wt list` aggregates status across all of them, and lifecycle
  # hooks run per-worktree setup/teardown (deps, .env, services).
  #
  # Nothing to add to nushell.nix: the shell integration - the `wt` wrapper
  # that actually cd's the session, plus completions - ships as
  # $out/share/nushell/vendor/autoload/wt.nu, and nushell already scans
  # /etc/profiles/per-user/yt/share/nushell/vendor/autoload. So do NOT run
  # `wt config shell install`; it would append a duplicate to a config file
  # this repo generates. nixpkgs 0.74.0 == upstream v0.74.0 (current).

  # ---- not in nixpkgs, built from packages/ai/ ----

  (callPackage ./ai/mempalace.nix { }) # local memory palace, MCP server is
  # `mempalace-mcp`. Pure-python + chromadb, all of it already in nixpkgs.

  (callPackage ./ai/fff-mcp.nix { }) # agent-oriented file/content search over
  # MCP. NOTE: the `fff` attribute in nixpkgs is dylanaraps' bash file manager,
  # a completely unrelated project - do not "simplify" this to `fff`.

  (callPackage ./ai/symposium.nix { }) # `cargo agents`: matches the workspace
  # dependency graph against plugin manifests and installs the skills, hooks and
  # MCP servers those crates ship for their own version. Rust-specific, and the
  # reason rtk is above - the recommendations registry points at it too.
  #
  # Configured declaratively in homes/programs/symposium.nix. Do NOT run
  # `cargo agents init`: at the default global hook scope it merges hook entries
  # straight into ~/.claude/settings.json, which is a mode-444 store symlink
  # here, so the write fails. That config pins hook-scope to "project" instead.

  (callPackage ./ai/crw.nix { }) # fastCRW: web scrape, crawl, map and search.
  # Puts `crw` on PATH; the `crw-mcp` binary from the same derivation is
  # registered in homes/programs/ai-mcp.nix.
  #
  # Wraps in both renderers - LightPanda (packages/ai/lightpanda.nix) and
  # chromium - so JS rendering works out of the box. That is where the ~700 MB
  # of closure comes from; the wrapper in crw.nix is the one place to cut it.
  #
  # Do NOT run `crw setup` or `npx crw-mcp install` - both write MCP entries
  # into ~/.claude/settings.json and prose into ~/.claude/CLAUDE.md, the two
  # generated files. The equivalent wiring is declared in nix already.

  nono # capability-based sandbox for agents: `nono run -- claude`.
  # NOTE: nixpkgs disables the command_policies tests because nono's ELF
  # resolver cannot find libc.so.6 for libgcc_s.so.1 - that feature is
  # effectively broken on NixOS. Filesystem/network confinement still works.
  # nixpkgs 0.71.0, upstream v0.74.0.
]
